AllCops:
  TargetRubyVersion: 3.2.3
  NewCops: enable
  SuggestExtensions: false

Style/AndOr:
  Enabled: true
  EnforcedStyle: always

Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: always
  EnforcedStyle: no_mixed_keys

Style/ParallelAssignment:
  Enabled: true

Layout/FirstArrayElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  Enabled: true

Layout/MultilineOperationIndentation:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/TrailingWhitespace:
  AllowInHeredoc: true
  Enabled: true

Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent

Layout/SpaceInLambdaLiteral:
  Enabled: true
  EnforcedStyle: require_space

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Layout/LineLength:
  Max: 100

Style/FrozenStringLiteralComment:
  Enabled: true

Naming/VariableNumber:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional

Style/SingleLineBlockParams:
  Methods:
    - reduce:
        - a
        - e
    - inject:
        - a
        - e

Style/Lambda:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  CountKeywordArgs: false
  Max: 5

Style/FetchEnvVar:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantArgument:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: true

Lint/NonLocalExitFromIterator:
  Enabled: false

Lint/NoReturnInBeginEndBlocks:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false
